DROP TABLE IF EXISTS `%TABLE_PREFIX%587_searchindex`;
DROP TABLE IF EXISTS `%TABLE_PREFIX%587_searchcache`;
DROP TABLE IF EXISTS `%TABLE_PREFIX%587_searchcacheindex_ids`;
DROP TABLE IF EXISTS `%TABLE_PREFIX%587_keywords`;